spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    datasource:
      data: classpath:data-mysql.sql
  thymeleaf:
    cache: false
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
  file:
    name: errors.log
server:
  port: 80
