spring:
  thymeleaf:
    prefix: classpath:/templates
  mvc:
    locale: pt_BR
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:petlandia}
    platform: mysql
    username: ${MYSQL_USER:petlandia}
    password: ${MYSQL_PASSWORD:petlandia}
    data: classpath:data-mysql.sql
    initialization-mode: always
  profiles:
    active: production
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 16MB
server:
  error:
    whitelabel:
      enabled: false
