name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean package -DskipTests spring-boot:repackage
    - name: Copy jar file
      run: |
        mkdir release
        mv target/webapp-0.0.1-SNAPSHOT.jar release/app.jar
    - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.SSH_USERNAME }}
          server: ${{ secrets.SSH_HOSTNAME }}
          ssh_private_key: ${{ secrets.SSH_KEY }} 
          local_path: './release/*'
          remote_path: '/home/petlandia'
    - name: restart application
      uses: fifsky/ssh-action@master
      with:
        command: sudo systemctl restart petlandia.service
        host: ${{ secrets.SSH_HOSTNAME }}
        user: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY}}
